my_list = [1, 2, 3, 4, 5, 'abc', 'k', '10.5']
print (my_list)
print (type(my_list))
print (len(my_list))
print (my_list[0])
print (my_list[-2])
print (my_list[1:4])
my_list.append(6)
print (my_list)
my_list.remove('abc')
print (my_list)
my_list.insert(2, 'new_item')
print (my_list)
my_list.pop(2)
print (my_list)