my_tuple = (1, 2, 3, 4, 5, 'abc', 'k', '10.5')
print(my_tuple)
print(type(my_tuple))
print(len(my_tuple))
print(my_tuple[0])
print(my_tuple[-2])
print(my_tuple[1:4])
list_from_tuple = list(my_tuple)
list_from_tuple.append(6)
print(list_from_tuple)
tuple_from_list = tuple(list_from_tuple)
print(tuple_from_list)